# Generated by Django 3.0.5 on 2020-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200425_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searches',
            field=models.CharField(max_length=500),
        ),
    ]
