# Generated by Django 3.0.5 on 2020-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200426_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searches',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
