# Generated by Django 3.0.5 on 2020-04-26 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200426_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searches',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
